# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1023, 537)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 531, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.female = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.female.setObjectName("female")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.female)
        self.gridLayout.addWidget(self.female, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(54, 108, 80);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.male = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.male.setObjectName("male")
        self.buttonGroup.addButton(self.male)
        self.gridLayout.addWidget(self.male, 5, 0, 1, 1)
        self.sumcalories = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.sumcalories.setStyleSheet("background-color: lime;\n"
" color: white;")
        self.sumcalories.setObjectName("sumcalories")
        self.gridLayout.addWidget(self.sumcalories, 2, 1, 1, 1)
        self.dishe = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.dishe.setObjectName("dishe")
        self.gridLayout.addWidget(self.dishe, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(63, 127, 94);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.small = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.small.setObjectName("small")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.small)
        self.gridLayout.addWidget(self.small, 6, 0, 1, 1)
        self.medium = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.medium.setObjectName("medium")
        self.buttonGroup_2.addButton(self.medium)
        self.gridLayout.addWidget(self.medium, 6, 1, 1, 1)
        self.big = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.big.setObjectName("big")
        self.buttonGroup_2.addButton(self.big)
        self.gridLayout.addWidget(self.big, 6, 2, 1, 1)
        self.calories = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.calories.setObjectName("calories")
        self.gridLayout.addWidget(self.calories, 1, 1, 1, 1)
        self.image = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 2, 0, 2, 1)
        self.List = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.List.setEnabled(False)
        self.List.setObjectName("List")
        self.gridLayout.addWidget(self.List, 3, 1, 1, 1)
        self.add = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setStyleSheet("background-color: lime")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.female.setText(_translate("Dialog", "kobieta"))
        self.label.setText(_translate("Dialog", "Nazwa posiłku"))
        self.male.setText(_translate("Dialog", "mężczyzna"))
        self.sumcalories.setText(_translate("Dialog", "Suma spożytych kalorii"))
        self.label_2.setText(_translate("Dialog", "Liczba kalorii"))
        self.small.setText(_translate("Dialog", "mała aktywność fizyczna"))
        self.medium.setText(_translate("Dialog", "średnia aktywność fizyczna"))
        self.big.setText(_translate("Dialog", "duża aktywność fizyczna"))
        self.add.setText(_translate("Dialog", "Dodaj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
